/*
Copyright 2018 Platform 9 Systems, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

// This file was automatically generated by informer-gen

package internalversion

import (
	time "time"

	sshprovider "github.com/platform9/ssh-provider/pkg/apis/sshprovider"
	internalclientset "github.com/platform9/ssh-provider/pkg/client/clientset_generated/internalclientset"
	internalinterfaces "github.com/platform9/ssh-provider/pkg/client/informers_generated/internalversion/internalinterfaces"
	internalversion "github.com/platform9/ssh-provider/pkg/client/listers_generated/sshprovider/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ProvisionedMachineInformer provides access to a shared informer and lister for
// ProvisionedMachines.
type ProvisionedMachineInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.ProvisionedMachineLister
}

type provisionedMachineInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewProvisionedMachineInformer constructs a new informer for ProvisionedMachine type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewProvisionedMachineInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredProvisionedMachineInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredProvisionedMachineInformer constructs a new informer for ProvisionedMachine type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredProvisionedMachineInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Sshprovider().ProvisionedMachines(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Sshprovider().ProvisionedMachines(namespace).Watch(options)
			},
		},
		&sshprovider.ProvisionedMachine{},
		resyncPeriod,
		indexers,
	)
}

func (f *provisionedMachineInformer) defaultInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredProvisionedMachineInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *provisionedMachineInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sshprovider.ProvisionedMachine{}, f.defaultInformer)
}

func (f *provisionedMachineInformer) Lister() internalversion.ProvisionedMachineLister {
	return internalversion.NewProvisionedMachineLister(f.Informer().GetIndexer())
}
